apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotions-cf
  labels:
    app: promotions-cf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: promotions-cf
  template:
    metadata:
      labels:
        app: promotions-cf
    spec:
      imagePullSecrets:
      - name: all-icr-io
      restartPolicy: Always
      containers:
      - name: promotions-cf
        image: us.icr.io/promotions-crns/promotions-cf:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: database_uri
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            cpu: "0.20"
            memory: "64Mi"
          requests:
            cpu: "0.10"        
            memory: "32Mi"
